USE IDvasive;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE if EXISTS LOCATIONS;
DROP TABLE if EXISTS PLANT_TYPE;
DROP TABLE if EXISTS PLANT_INSTANCE;
DROP TABLE if EXISTS REPORT;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE LOCATIONS (
    LOCATION_ID int AUTO_INCREMENT NOT NULL,
    LONGITUDE DOUBLE NOT NULL,
    LATITUDE DOUBLE NOT NULL,
    primary key (LOCATION_ID)
); 

CREATE TABLE PLANT_TYPE (
    PLANT_ID int AUTO_INCREMENT NOT NULL,
    PLANT_NAME VARCHAR(255) NOT NULL,
    primary key (PLANT_ID)
);

CREATE TABLE PLANT_INSTANCE (
    PLANT_INSTANCE_ID int AUTO_INCREMENT NOT NULL,
    PLANT_TYPE_ID int NOT NULL,
    LOCATION_ID int NOT NULL,
    CONSTRAINT PLANT_INSTANCE_pk primary key (PLANT_INSTANCE_ID),
    CONSTRAINT PLANT_INSTANCE_fk_PLANT_ID FOREIGN KEY (PLANT_TYPE_ID)
        REFERENCES PLANT_TYPE(PLANT_ID),
    CONSTRAINT PLANT_INSTANCE_fk_LOCATION_ID FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS(LOCATION_ID)   
);


CREATE TABLE REPORT (
    REPORT_ID int AUTO_INCREMENT NOT NULL,
    PLANT_INSTANCE_ID int NOT NULL,
    TIME_CREATED DATETIME, 
    SUPPLIED_DESCRIPTION TEXT NOT NUlL,
    SUPPLIED_IMAGE LONGBLOB,
    CONSTRAINT REPORT_PK primary key (REPORT_ID),
    CONSTRAINT REPORT_FK_PLANT_INSTANCE_ID FOREIGN KEY (PLANT_INSTANCE_ID)
        REFERENCES PLANT_INSTANCE(PLANT_INSTANCE_ID)
);