# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lT0ht2WAkzFqVrrrzuynpBzolxu2qqi0

Import packages
"""

import pandas as pd
import requests
import shutil
import pathlib
from os import listdir
from os.path import isfile, join


"""Import and check data"""


folderpath = './source/'
output = './pictures/'

onlyfiles = [f for f in listdir(folderpath) if isfile(join(folderpath, f))]


print(onlyfiles)


"""Function we can call repeatedly"""


def get_image(url, count_val, species):
  filename = species + '/' + species + "_" + str(count_val) + '.jpg'
  img = requests.get(url, stream=True)
  if img.status_code == 200:
    img.raw.decode_content = True

    # using open to save the file to the drive
    with open(output+filename, 'wb') as f:
        shutil.copyfileobj(img.raw, f)
        # This shows that we have no errors and that the images are being downloaded
        print('Image sucessfully Downloaded: ', output+filename)
  else:
    print('Image Couldn\'t be retreived')




for file in onlyfiles:
  """Select the url column"""

  species = file.split('.')[0]

  df = pd.read_csv(folderpath + file)
  df_url = [x for x in df.image_url]

  try:
    pathlib.Path(output + species + '/').mkdir(parents=True, exist_ok=True)
  except:
    print("failed to create " + output + species + '/')

  for x_val, x in enumerate(df_url):
    get_image(x, x_val, species)
    if x_val > 5:
      break

